# Generated by Django 5.1 on 2024-09-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='active_users',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
