# Generated by Django 5.1 on 2024-09-04 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='host',
            field=models.CharField(default='Unknown', max_length=55),
        ),
    ]
